---
- name: api-v1
  route: api/v1/
  gitfilter: 
    branch: master
    version: "0.1.57"
  deploymentpolicy: locked
  targettags:
  - name: environment
    value: prod
  - name: servicefamily
    value: services-external
  - name: servicegroup
    value: api