---
- name: api
  routes:
  - route: api/
    gitfilter: branch:prod
    deploymentpolicy: locked
    targettags:
    - name: environment
      value: prod
    - name: servicefamily
      value: services-external
    - name: servicegroup
      value: api
  - route: api/v1/
    gitfilter: branch:prod
    deploymentpolicy: manual
    targettags:
    - name: environment
      value: prod
    - name: servicefamily
      value: services-external
    - name: servicegroup
      value: api
  - route: api/v2/
    gitfilter: branch:dev
    deploymentpolicy: onbuild
    targettags:
    - name: environment
      value: prod
    - name: servicefamily
      value: services-external
    - name: servicegroup
      value: api
- name: api.profile
  routes:
  - route: api/profile/v1
    gitfilter: tag:v1
    deploymentpolicy: locked
    targettags:
    - name: environment
      value: prod
    - name: servicefamily
      value: services-external
    - name: servicegroup
      value: api
  - route: api/profile/v2
    gitfilter: branch:prod
    deploymentpolicy: manual
    targettags:
    - name: environment
      value: prod
    - name: servicefamily
      value: services-external
    - name: servicegroup
      value: api
