---
- name: api
  routes:
  - route: api/v1/
    gitfilter: 
      branch: master
      version: "0.1.57"
    deploymentpolicy: locked
    targettags:
    - name: environment
      value: prod
    - name: servicefamily
      value: services-external
    - name: servicegroup
      value: api

  - route: api/v2/
    gitfilter: 
      branch: master
      version: latest
    deploymentpolicy: onbuild
    targettags:
    - name: environment
      value: prod
    - name: servicefamily
      value: services-external
    - name: servicegroup
      value: api
