---
- name: Configure traefik nodes
  hosts: traefik
  tasks:
    - name: Install docker
      yum:
        name: docker

- name: Configure traefik nodes
  hosts: traefik
  serial: 1
  tasks:
    - name: deploy config file
      template:
        src: traefik.toml
        dest: $PWD/traefik.toml
      register: traefik_config
      notify: Deploy or redeploy docker container 
      
#    - block:
#        #Trying to idempodency with handlers instead
#      when: traefik_config.changed and not docker_created.changed
  handlers:
    - name: Deploy or redeploy docker container
      docker_container:
        name: traefik
        image: traefik
        state: present
        pull: yes
        restart_policy: always
        published_ports:
          - 80:80
          - 8080:8080
        volumes:
          - $PWD/traefik.toml:/etc/traefik/traefik.toml
      register: docker_created