---
- name: Configure traefik nodes
  hosts: traefik
  tasks:
    - name: Install docker engine
      yum:
        name: docker
    - name: Make sure docker engine is running
      service:
        name: docker
        state: started
    - name: Install docker support for python
      pip:
        name: docker-py

- name: Configure traefik nodes
  hosts: traefik
  serial: 1
  tasks:
    - name: create traefik config file folder
      file:
        name: /opt/traefik
        state: directory
    - name: deploy config file
      template:
        src: traefik.toml
        dest: /opt/traefik/traefik.toml
      register: traefik_config
      notify: Deploy or redeploy docker container 
    - name: check if docker is running
      shell: docker ps -q
      register: docker_ps
      changed_when: docker_ps.stdout == ''
      notify: Deploy or redeploy docker container
#    - block:
#        #Trying to idempodency with handlers instead
#      when: traefik_config.changed and not docker_created.changed
  handlers:
    - name: Deploy or redeploy docker container
      docker_container:
        name: traefik
        image: traefik
        state: started
        pull: yes
        restart_policy: always
        published_ports:
          - 80:80
          - 8080:8080
        volumes:
          - /opt/traefik/traefik.toml:/etc/traefik/traefik.toml
      register: docker_created