defaultEntryPoints = ["http80"]
[entryPoints]
  [entryPoints.http80]
  address = ":80"

###
# web configuration
[web]
address = ":8080"



logLevel = "DEBUG"

################################################################
# Consul Catalog configuration backend
################################################################

[consulCatalog]

endpoint = "10.0.0.131:8500"

# Default domain used.
#
# Optional
#
domain = "backend.traefik.local"

# Prefix for Consul catalog tags
#
# Optional
#
# prefix = "traefik"

# Constraints
#
# Optional
#
# constraints = ["tag==api", "tag==he*ld"]
# Matching with containers having this tag: "traefik.tags=api,helloworld"

